### ISSUE TITLE
i made a joke pwoject 

### ISSUE THREAD

**Issue by joshualeejunyi** [Daniel-Liu-c0deb0t/uwu#23]
my fwiend intwoduced youw fastest uwuifiew in the west to me and i jokingwy said that i shouwd c-cweate a ~~mawwawe~~ p-pwogwam that uwuifies as you type! enjoyed doing it and i'm wwiting this issue nyow with it wunning hehe.

[wink is here](https://github.com/joshualeejunyi/uwu-joke)

**Comment by joshualeejunyi** [comment]
just an update: seems buggy on certain environments, but will get around to fixing it!

**Comment by Daniel-Liu-c0deb0t** [comment]
thank you for this awesome project, ill add it to the readme
