### ISSUE TITLE
nyani??!?!??!?!

### ISSUE THREAD

**Issue by ghost** [Daniel-Liu-c0deb0t/uwu#26]
e-ewwor instawwing o-on em1 makbuk p-pwo ('_')

```error[E0432]: unresolved import `uwuifier::uwuify_sse`
 --> /Users/myrealnameudontsee/.cargo/registry/src/github.com-1ecc6299db9ec823/uwuify-0.2.2/src/main.rs:1:5
  |
1 | use uwuifier::uwuify_sse;
  |     ^^^^^^^^^^^^^^^^^^^^ no `uwuify_sse` in the root

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: failed to compile `uwuify v0.2.2`, intermediate artifacts can be found at `/var/folders/q3/v84w5_7j11g__d2g4b0z5sqh0000gp/T/cargo-install2HXfsc`
```

also i uwuified the first sentence by hand lmao

**Comment by ghost** [comment]
formatting took an f dont mind it

**Comment by Daniel-Liu-c0deb0t** [comment]
ur cpu probably doesn't have sse support (eg., recent-ish intel or amd cpu) :'(

do u have an m1 mbp?

**Comment by ghost** [comment]
<img width="203" alt="image" src="https://user-images.githubusercontent.com/72974062/124085399-9d488c80-da6d-11eb-98de-0d754e59c6da.png">
yup

**Comment by Daniel-Liu-c0deb0t** [comment]
m1, which is an arm cpu, isn't currently supported rn :'(
pain

**Comment by ghost** [comment]
awwwwwwww :(:(:(:(:(:(:(
