### ISSUE TITLE
Formatting does not work properly when piping in neofetch

### ISSUE THREAD

**Issue by Akari202** [Daniel-Liu-c0deb0t/uwu#37]
Title says it all. I piped neofetch in and it broke the formatting, Im assuming uwuify is breaking the ASCII character return 
escape codes that neofetch uses

## Expected
<img width="200" alt="Screen Shot 2022-07-18 at 00 38 29" src="https://user-images.githubusercontent.com/84194114/179451192-c7399ea0-e6f6-4bef-826b-330e64edf5d4.png">

## Actual
<img width="200" alt="Screen Shot 2022-07-18 at 00 41 33" src="https://user-images.githubusercontent.com/84194114/179451220-45a800eb-920c-4542-b093-27950ebc6192.png">

**Comment by unclamped** [comment]
Can reproduce, just now tried doing `neofetch | uwuify | lolcat` and it looks just like the screenshot.

**Comment by gitautas** [comment]
It's not the escape codes, it's the emoticons that are inserted in place result in excess whitespace. This is also completely out of scope for this project and shouldn't be an issue.
