### ISSUE TITLE
How to use lib with strings?

### ISSUE THREAD

**Issue by ShadowMitia** [Daniel-Liu-c0deb0t/uwu#5]
Hello!

I want to use the lib in a bot, to try out, but it seems to be able to only use files/stdin.
Is there an easy way to use strings with this lib?

Thanks in advance!

**Comment by Daniel-Liu-c0deb0t** [comment]
right now this isn't possible. ill need to publish the core uwuify function as a separate crate so you can include it in rust programs, but i might not get around to it

**Comment by ShadowMitia** [comment]
Fair enough^^
I'm using `uwu_ify_sse` from the crate for now, it's good enough for me right now^^

**Comment by Daniel-Liu-c0deb0t** [comment]
oh cool, yes that works too

just make sure you pass large buffers for the `temp_bytes` cuz in the worst case, it is possible for each of the 4 passes to approximately double the size of the input buffer. right now it will just panic if you pass it a buffer that is too small. see `src/main.rs` for an example of how `uwu_ify_sse` is called

**Comment by ShadowMitia** [comment]
Thanks for the tip!
I didn't understand why you need two temp buffers. Would you mind clarifying that?

**Comment by Daniel-Liu-c0deb0t** [comment]
sure. each pass uses one of the temp buffers for input and the other for output. of course, you could make the `bytes` buffer mutable and overwrite it, but i thought it would be easier for the user to not have to worry about the `bytes` buffer has a certain size or alignment (eventually i didn't require a certain alignment for any of the buffers though) or having the stuff they pass in be modified. also, the temp buffers were supposed to be an implementation detail (ie, allocated in the `uwu_ify_sse` function, so you would only pass in a immutable `bytes` slice with no requirements on its size), but to reduce allocations i moved it out.

**Comment by Daniel-Liu-c0deb0t** [comment]
alright, just published a new release that should make this a lot easier to use

you can put `uwuify = "^0.2"` in your `Cargo.toml` to include uwuify as a library. take a look at the readme for instructions on how to use it. also there's docs at: https://docs.rs/uwuify/0.2.0/uwuifier/

**Comment by jRimbault** [comment]
Would you be comfortable exposing that [kind][0] of API ?

```
pub fn uwuify(input: &str) -> String;
```

[0]: https://github.com/yaahc/uwubot/blob/74ee2a36517e6e325c3095304751accc97103568/src/uwu.rs

**Comment by Daniel-Liu-c0deb0t** [comment]
sure, im working on it

Edit: done and published in version `0.2.1`

**Comment by ShadowMitia** [comment]
Oh that example is great, thanks!
